apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.3.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: openldap-admin
          ports:
            - name: ldap
              containerPort: 389
            - name: ldaps
              containerPort: 636
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
            - name: config
              mountPath: /etc/ldap/slapd.d
            - name: certs
              mountPath: /container/service/slapd/assets/certs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openldap-data
        - name: config
          persistentVolumeClaim:
            claimName: openldap-config
        - name: certs
          emptyDir: {}
