apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloack
resources:
  - secret-ldap-admin.yaml
  - pvc.yaml
  - deployment-openldap.yaml
  - service-openldap.yaml
  - deployment-phpldapadmin.yaml
  - service-phpldapadmin.yaml
