apiVersion: v1
kind: Secret
metadata:
  name: openldap-admin
  labels:
    app: openldap
stringData:
  LDAP_ORGANISATION: kubedevops
  LDAP_DOMAIN: ldap.kubedevops.com
  LDAP_ADMIN_PASSWORD: mondariz10
