apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  labels:
    app: phpldapadmin
spec:
  selector:
    app: phpldapadmin
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
