apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  labels:
    app: phpldapadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: openldap
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
          ports:
            - name: http
              containerPort: 80
