apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data
  labels:
    app: openldap
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-config
  labels:
    app: openldap
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
