apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloack-issuer
spec:
  acme:
    email: akaronte@hotmail.com
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: keycloack-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
