apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
spec:
  hostname:
    hostname: {{ .Values.hostname }}
  http:
    httpEnabled: true
    httpPort: 8080
    tlsSecret: {{ .Values.tlsSecret }}
  ingress:
    enabled: false