kind: Service
apiVersion: v1
metadata:
  name: example-keycloak-service
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
  selector:
    app: keycloak
    app.kubernetes.io/instance: example-keycloak

