# Valores por defecto del chart keycloack
# Puedes sobrescribirlos con --set o un archivo values personalizado

hostname: "keycloack.ingress.kube2.okd.piensoluegoinstalo.com"
tlsSecret: keycloack-tls-ingress
